### ISSUE TITLE
@babel/plugin-transform-private-methods causing problems

### ISSUE THREAD

**Issue by jonaspiela** [dnwjn/gatsby-plugin-plausible#21]
Hi @dnwjn,

This line is causing me headaches:

https://github.com/dnwjn/gatsby-plugin-plausible/blob/9c5f3eec5dc6f9865c3cf7bc14a8f43b80c1d390/package.json#L47

```
 ERROR  UNKNOWN

Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: /workspace/node_modules/@dnwjn/gatsby-plugin-plausible/node_modules/minimatch/dist/commonjs/ast.js#86:
Class private methods are not enabled. Please add `@babel/plugin-transform-private-methods` to your
configuration.
```

It wasn't part of the original plausiple plugin and I don't see where you are using private methods.

Is it really needed? Happy to help get rid of it, if possible.

**Comment by dnwjn** [comment]
Hi @jonaspiela,

I researched the plugin, and I came to the conclusion that it was not needed. Together with some other minor improvements I took the liberty of removing the plugin as well (#29).

Thank you for your input! And you're absolutely welcome to keep contributing, I'd be happy to look into any future proposals/PRs you might have! :)

**Comment by jonaspiela** [comment]
Oh, I saw this too late. Maybe I should enable email notifications again. I just added #33. Anyhow, in my issue I thought I had mentioned `minimatch` instead. Because in my view, this is the actual problem...
